name: Update Image Gallery
on:
  workflow_dispatch:
  push:
    paths:
      - 'Images/**'

jobs:
  update-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Generate Markdown
        run: |
          cat > generate_markdown.py << 'EOF'
          import os
          
          def generate_image_markdown(image_dir="Images"):
              markdown_lines = ["# Loss Accuracy Plots\n"]
              image_files = [f for f in os.listdir(image_dir) if f.endswith(".png")]
              image_files.sort()
              
              for image in image_files:
                  params = image.replace("loss_accuracy_plot_", "").replace(".png", "").strip("()")
                  markdown_lines.append(f"![{params}]({image_dir}/{image})\n")
              
              return "".join(markdown_lines)
          
          with open("PLOTS.md", "w") as f:
              f.write(generate_image_markdown())
          EOF
          python generate_markdown.py
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add PLOTS.md
          git commit -m "Update plots gallery" || exit 0
          git push
